# Generated by Django 5.1 on 2024-08-17 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relationship_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_add_book", "Can add a new book"),
                    ("can_change_book", "Can change the book details"),
                    ("can_delete_book", "Can delete a book"),
                ]
            },
        ),
    ]
